Repository Requisitos-de-Software/2020.1-Promobit, pull requests merged in 2020-09, with the labels that each got.

#2 Documento de planejamento e README adicionados
  README.md
  assets/integrantes/Igor.png
  assets/integrantes/Marcelo.png
  assets/integrantes/Rhuan.png
  assets/integrantes/ThiagoG.png
  assets/integrantes/ThiagoL.png
  assets/logos/Discord.png
  assets/logos/GitHub.png
  assets/logos/Lucidchart.png
  assets/logos/Office365.png
  assets/logos/Promobit.png
  assets/logos/Telegram.png
  assets/logos/ZenHub.png
  assets/tabela_horarios/tabela_horarios.jpg
  assets/tabela_horarios/tabela_horarios_legenda1.jpg
  assets/tabela_horarios/tabela_horarios_legenda2.jpg
  docs/planejamento.md
Labels: documentação

#4 Estrutura basica do mkdocs criada
  README.md
  docs/index.md
  mkdocs.yml
Labels: documentação, melhoria

#5 Criando CI
  .github/workflows/ci.yml
Labels: melhoria

#7 Configurar docs
  README.md
  docs/assets/icons/monetization_on.png
  docs/assets/integrantes/Igor.png
  docs/assets/integrantes/Marcelo.png
  docs/assets/integrantes/Rhuan.png
  docs/assets/integrantes/ThiagoG.png
  docs/assets/integrantes/ThiagoL.png
  docs/assets/logos/Discord.png
  docs/assets/logos/GitHub.png
  docs/assets/logos/Lucidchart.png
  docs/assets/logos/Office365.png
  docs/assets/logos/Promobit.png
  docs/assets/logos/Telegram.png
  docs/assets/logos/ZenHub.png
  docs/assets/tabela_horarios/tabela_horarios.jpg
  docs/assets/tabela_horarios/tabela_horarios_legenda1.jpg
  docs/assets/tabela_horarios/tabela_horarios_legenda2.jpg
  docs/index.md
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: melhoria

#6 Documentos de pré-rastreabilidade
  docs/assets/rich_picture/configuracoes.png
  docs/assets/rich_picture/cupons.png
  docs/assets/rich_picture/forum.png
  docs/assets/rich_picture/geral.png
  docs/assets/rich_picture/ofertas.png
  docs/assets/rich_picture/usuarios.png
  docs/planejamento.md
  docs/pre_rastreabilidade/rich_pictures.md
  mkdocs.yml
Labels: documentação

#8 Adição aba de apresentações
  docs/apresentacoes.md
  mkdocs.yml
Labels: documentação, melhoria

#9 Adição de ferramentas ao planejamento do projeto
  docs/assets/logos/Docs.png
  docs/assets/logos/Overleaf.png
  docs/planejamento.md
Labels: documentação

#10 Adição aba de atas
  docs/atas/reuniao-13-09-2020.md
  mkdocs.yml
Labels: documentação

#12 Documentacao/personas
  docs/assets/personas/Rafael.jpg
  docs/assets/personas/kelly.jpg
  docs/assets/personas/vitinho.jpg
  docs/elicitacao/introspeccao.md
  docs/elicitacao/personas.md
  mkdocs.yml
Labels: documentação

#16 Adição ata de reunião do dia 21/09/2020
  docs/atas/reuniao-21-09-2020.md
  mkdocs.yml
Labels: documentação

#15 Criação documento de questionário
  docs/assets/resultados_questionario/1.png
  docs/assets/resultados_questionario/10.png
  docs/assets/resultados_questionario/2.png
  docs/assets/resultados_questionario/3.png
  docs/assets/resultados_questionario/4.png
  docs/assets/resultados_questionario/5.png
  docs/assets/resultados_questionario/6.png
  docs/assets/resultados_questionario/7.png
  docs/assets/resultados_questionario/8.png
  docs/assets/resultados_questionario/9.png
  docs/elicitacao/questionario.md
  mkdocs.yml
Labels: documentação

#18 Adição do documento de priorização
  docs/priorizacao.md
  mkdocs.yml
Labels: documentação

#19 Adição apresentação de elicitação e priorização
  docs/apresentacoes.md
Labels: documentação
