Repository Requisitos-de-Software/2020.1-Promobit, pull requests merged in 2020-10, with the labels that each got.

#21 Mudança dos links das apresentações para o youtube
  docs/apresentacoes.md
Labels: melhoria

#20 Adição ata de reunião do dia 30/09/2020
  docs/atas/reuniao-30-09-2020.md
  mkdocs.yml
Labels: documentação

#22 Adição do documento contendo todos os requisitos
  docs/elicitacao/brainstorming.md
  docs/elicitacao/requisitos.md
  mkdocs.yml
Labels: documentação, melhoria

#23 Correção de links das apresentações
  docs/apresentacoes.md
Labels: documentação, melhoria

#24 Adição casos de uso
  docs/assets/casos_de_uso/configuracoes.png
  docs/assets/casos_de_uso/pesquisar_oferta.png
  docs/assets/casos_de_uso/sugerir_cupom.png
  docs/assets/casos_de_uso/sugerir_oferta.png
  docs/assets/casos_de_uso/sugerir_topico_forum.png
  docs/modelagem/caso_de_uso.md
  mkdocs.yml
Labels: documentação

#25 Adição dos cenários
  docs/modelagem/cenarios.md
  mkdocs.yml
Labels: documentação

#26 Criação do documento de léxico
  docs/modelagem/lexico.md
  mkdocs.yml
Labels: documentação

#27 Adição do documento de especificação suplementar baseado no SRS
  docs/modelagem/suplementar.md
  mkdocs.yml
Labels: documentação

#28 Priorização utilizando o MoSCoW
  docs/elicitacao/requisitos.md
  docs/priorizacao/first_thing_first.md
  docs/priorizacao/moscow.md
  mkdocs.yml
Labels: documentação

#29 Adição da terceira apresentação
  docs/apresentacoes.md
Labels: documentação

#30 Adição da ata da reunião do dia 13/10/2020
  docs/atas/reuniao-13-10-2020.md
Labels: documentação

#32 NFR Framework
  docs/assets/NFR/nfr-confiabilidade-propagado.png
  docs/assets/NFR/nfr-confiabilidade.png
  docs/assets/NFR/nfr-disponibilidade-propagado.png
  docs/assets/NFR/nfr-disponibilidade.png
  docs/assets/NFR/nfr-manutenibilidade-propagado.png
  docs/assets/NFR/nfr-manutenibilidade.png
  docs/assets/NFR/nfr-performance-propagado.png
  docs/assets/NFR/nfr-performance.png
  docs/assets/NFR/nfr-portabilidade-propagado.png
  docs/assets/NFR/nfr-portabilidade.png
  docs/assets/NFR/nfr-seguranca-propagado.png
  docs/assets/NFR/nfr-seguranca.png
  docs/assets/NFR/nfr-usabilidade-propagado.png
  docs/assets/NFR/nfr-usabilidade.png
  docs/modelagem/nfr_framework.md
  docs/modelagem/suplementar.md
  mkdocs.yml
Labels: documentação

#31 Adição de novos casos de uso
  docs/assets/casos_de_uso/interagir_oferta.png
  docs/assets/casos_de_uso/lista_de_desejos.png
  docs/assets/casos_de_uso/realizar_cadastro.png
  docs/assets/casos_de_uso/realizar_login.png
  docs/assets/casos_de_uso/visualizar_topico_forum.png
  docs/modelagem/caso_de_uso.md
Labels: documentação

#34 Correção nos documentos de modelagem
  docs/assets/NFR/nfr-geral.png
  docs/assets/NFR/nfr-seguranca-propagado.png
  docs/assets/NFR/nfr-seguranca.png
  docs/assets/NFR/nfr-usabilidade-propagado.png
  docs/assets/NFR/nfr-usabilidade.png
  docs/assets/casos_de_uso/sugerir_cupom.png
  docs/assets/casos_de_uso/sugerir_topico_forum.png
  docs/modelagem/caso_de_uso.md
  docs/modelagem/nfr_framework.md
  docs/modelagem/suplementar.md
Labels: documentação

#35 Melhorias gerais nos documentos
  README.md
  docs/assets/integrantes/ThiagoL.png
  docs/assets/integrantes/Thiago_G.png
  docs/assets/integrantes/Thiago_L.png
  docs/assets/logos/LiveShare.png
  docs/assets/logos/Overleaf.png
  docs/assets/logos/Sheets.png
  docs/assets/logos/Slides.png
  docs/assets/logos/Teams.png
  docs/assets/logos/VisualStudioCode.png
  docs/assets/logos/ZenHub.png
  docs/elicitacao/questionario.md
  docs/index.md
  docs/modelagem/caso_de_uso.md
  docs/planejamento.md
  docs/pre_rastreabilidade/rich_pictures.md
  docs/priorizacao.md
Labels: documentação, melhoria

#36 Backlog
  docs/assets/backlog_de_produto/backlog.png
  docs/elicitacao/brainstorming.md
  docs/elicitacao/requisitos.md
  docs/modelagem/backlog_do_produto.md
  docs/modelagem/caso_de_uso.md
  docs/priorizacao/moscow.md
  mkdocs.yml
Labels: documentação

#37 Adição da quarta apresentação do projeto
  docs/apresentacoes.md
Labels: documentação, melhoria
